modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="oresabovediamonds" #mandatory
version="6.1.0" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/ores-above-diamonds" #optional
displayName="Ores Above Diamonds" #mandatory
logoFile="oresabovediamonds_logo.png" #optional
# A text field displayed in the mod UI
authors="§dSquidsword" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds the §dAmethyst§r and §5Black Opal§r which are respectively §d3x§r and §59x§r rarer than diamonds.
Both have its own set of balanced armors and tools.

It's recommended to download Overloaded Armor Bar along with this mod.
https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar/

The mod doesn't have built in retrogen support. This means that ores will not spawn in already loaded chunks. Venture far into unexplored lands to have a chance at finding them.

Special thanks to §6CriativeMan1§r for making the art for this mod!
'''
# Here's another dependency
[[dependencies.oresabovediamonds]]
    modId="overloadedarmorbar"
    mandatory=false
    versionRange="[3.0.0b,)"
    ordering="AFTER"
    side="CLIENT"
